"""The offline drive of a :class:`PartnerSession` — canned user turns on a timer.

The partner loop's claims — beliefs extracted per turn, collisions surfaced as
divergence cards, the blocked belief held out of the pool — are the ones a
judge cannot check by watching a live demo, because a live demo's inputs are
the team's. So the loop is exercised the only checkable way: a scripted set of
user turns drives the *real* ``PartnerSession`` — real extraction gates, real
contradiction detection, real append-only session store — and the run writes a
transcript that records, per turn, what was extracted, what was dropped and
why, and which collisions were raised.

**Input and output are deliberately different directories.**

``fixtures/interviews/<script>.json``
    Hand-authored. What the user types, turn by turn. This is a script, and it
    is supposed to be.

``fixtures/transcripts/<script>.json``
    **Generated by an actual run of this module, and never hand-edited.** The
    harness overwrites the file wholesale on every run, so an edit survives
    exactly until the next run and shows up in the diff of the one after it.
    Metric scripts read these and import nothing from this package, which is
    what makes any published number reproducible by someone who does not trust
    the application.

**Why the answers arrive on a timer.** A working session is paced by a person.
A harness that dumps twenty turns into the loop in four milliseconds is
exercising a different system than the one a person uses — the streaming path
never has to hold anyone's attention, and a first-visible-token figure measured
under that load is a figure about nothing. The pace is declared per script in
characters per minute, the run records whether it was paced and by what
acceleration factor, and any timing derived from a paced run says so.

**Why the harness watches for exceptions the session swallows.**
``Interviewer.compose_follow_up`` and ``PartnerSession._work_step`` catch
everything and degrade gracefully. That is right for a live session — losing
one clarifier is cheaper than hanging with a person waiting — and it is exactly
wrong for a transcript about to be published as evidence. A missing cassette
would otherwise yield a clean-looking run with zero follow-ups and no sign that
the model was never consulted. So the client is wrapped: every swallowed
failure is recorded, the run aborts, and no transcript is written. A number
produced by silent failure is the same defect as a number typed in by hand.
"""

from __future__ import annotations

import hashlib
import json
import time
from collections.abc import Callable, Iterator, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from baraza.interview.interviewer import (
    FOLLOW_UP_BUDGET,
    PartnerSession,
    PartnerTurnOutcome,
    TurnPlan,
)
from baraza.interview.session_store import SessionStore
from baraza.llm import LLMClient, LLMResponse
from baraza.reconcile.agenda import Agenda
from baraza.schema.claim import Claim
from baraza.schema.session import Turn
from baraza.schema.temporal import to_iso
from baraza.schema.visibility import Audience

__all__ = [
    "CannedTurn",
    "PartnerScript",
    "ScriptError",
    "ReplayPreconditionError",
    "PartnerReplayHarness",
    "PartnerReplayResult",
    "TRANSCRIPT_SCHEMA",
    "SCRIPT_DIR",
    "TRANSCRIPT_DIR",
    "load_script",
    "available_scripts",
]

_REPO = Path(__file__).resolve().parents[3]
SCRIPT_DIR = _REPO / "fixtures" / "interviews"
TRANSCRIPT_DIR = _REPO / "fixtures" / "transcripts"

TRANSCRIPT_SCHEMA = "baraza.partner-transcript.v1"
"""Versioned because metric scripts are not allowed to import this module and
therefore cannot follow a field rename. A scorer checks this string and refuses
a transcript it does not recognize rather than averaging whatever it finds."""

_TRANSCRIPT_NOTE = (
    "Generated by an actual replay run of src/baraza/interview/replay.py. Not "
    "hand-authored and not hand-edited: the harness rewrites this file whole on "
    "every run, so an edit survives until the next run and is visible in the "
    "diff after it. Any figure published from this file is computed by a "
    "standalone script that imports nothing from the application package."
)


class ScriptError(ValueError):
    """A script fixture cannot drive an honest run."""


class ReplayPreconditionError(RuntimeError):
    """The run cannot produce an honest transcript, so it produced none.

    Raised for a missing cassette, an auth failure, or any other model-layer
    error the session swallowed. Never downgraded to a warning: a transcript
    written after a swallowed failure is a fabricated measurement wearing a
    generated file's clothes.
    """


# ---------------------------------------------------------------- the script


@dataclass(frozen=True, slots=True)
class CannedTurn:
    """One scripted user turn."""

    text: str
    note: str = ""


@dataclass(frozen=True, slots=True)
class PartnerScript:
    """One scripted user, plus the pace their turns are delivered at."""

    script_id: str
    description: str
    chars_per_minute: int
    min_pause_ms: int
    max_pause_ms: int
    turns: tuple[CannedTurn, ...]
    source_path: Path
    fixture_sha256: str
    """Digest of the fixture bytes, stamped into the transcript. Ties a
    generated transcript to the exact script that produced it, so "we changed
    the turns and reran" is visible rather than inferable."""

    def validate(self) -> None:
        if not self.turns:
            raise ScriptError(f"{self.source_path}: no canned turns")
        for index, turn in enumerate(self.turns):
            if not turn.text.strip():
                raise ScriptError(
                    f"{self.source_path}: turn #{index} is empty. An empty "
                    "user turn exercises nothing and would still consume an "
                    "agent turn."
                )

    def typing_delay_ms(self, text: str, *, speed: float = 1.0) -> int:
        """How long this scripted user would take to type ``text``.

        Clamped at both ends. The floor keeps a two-word turn from arriving
        instantly, which reads as a machine rather than a person; the ceiling
        keeps a 300-character turn from stalling a demo for a minute. Both
        bounds are declared in the fixture and both are recorded in the
        transcript, so nobody has to guess whether a gap between turns is a
        measurement or a stage direction.
        """
        if speed <= 0:
            return 0
        raw = (len(text) / max(self.chars_per_minute, 1)) * 60_000.0
        clamped = max(self.min_pause_ms, min(self.max_pause_ms, raw))
        return int(clamped / speed)

    def describe(self) -> str:
        lengths = [len(t.text.strip()) for t in self.turns]
        return (
            f"{self.script_id}: {len(self.turns)} canned turns, "
            f"{min(lengths)}–{max(lengths)} chars, "
            f"{self.chars_per_minute} cpm"
        )


def available_scripts(directory: Path | str = SCRIPT_DIR) -> list[str]:
    return sorted(p.stem for p in Path(directory).glob("*.json"))


def load_script(
    name_or_path: str | Path, *, directory: Path | str = SCRIPT_DIR
) -> PartnerScript:
    """Load and validate a script fixture.

    Accepts a bare name (``builder-session``) or a path. Validation runs here
    rather than at first use so a bad fixture fails before a session is opened
    and before any event is appended to the log.
    """
    candidate = Path(name_or_path)
    path = (
        candidate
        if candidate.suffix == ".json"
        else Path(directory) / f"{candidate}.json"
    )

    if not path.exists():
        known = available_scripts(directory)
        raise FileNotFoundError(
            f"no script fixture at {path}. "
            f"Known scripts in {directory}: {known or '(none)'}"
        )

    raw = path.read_bytes()
    payload = json.loads(raw.decode("utf-8"))
    typing = payload.get("typing") or {}

    script = PartnerScript(
        script_id=payload["script_id"],
        description=payload.get("description", ""),
        chars_per_minute=int(typing.get("chars_per_minute", 240)),
        min_pause_ms=int(typing.get("min_pause_ms", 400)),
        max_pause_ms=int(typing.get("max_pause_ms", 6000)),
        turns=tuple(
            CannedTurn(text=t["text"], note=t.get("note", ""))
            for t in payload.get("turns", [])
        ),
        source_path=path,
        fixture_sha256=hashlib.sha256(raw).hexdigest(),
    )
    script.validate()
    return script


# ------------------------------------------------------- the failure watcher


class _FailureWatchingClient(LLMClient):
    """Delegating client that remembers what the session chose to forget.

    See the module docstring. This exists because a swallowed ``CassetteMiss``
    and a genuinely quiet turn are indistinguishable from inside the loop, and
    one of them invalidates the transcript.
    """

    def __init__(self, inner: LLMClient):
        self.inner = inner
        self.failures: list[tuple[str, str]] = []
        self.sources: set[str] = set()
        self.model_ids: set[str] = set()
        self.calls = 0

    def _record(self, response: LLMResponse) -> LLMResponse:
        self.calls += 1
        self.sources.add(response.source)
        self.model_ids.add(response.model_id)
        return response

    def generate(self, **kwargs: Any) -> LLMResponse:
        try:
            return self._record(self.inner.generate(**kwargs))
        except Exception as exc:  # noqa: BLE001 - recorded, then re-raised
            self.failures.append((f"generate(role={kwargs.get('role')!r})", str(exc)))
            raise

    def stream(self, **kwargs: Any) -> Iterator[str]:
        try:
            yield from self.inner.stream(**kwargs)
        except Exception as exc:  # noqa: BLE001
            self.failures.append((f"stream(role={kwargs.get('role')!r})", str(exc)))
            raise


# ------------------------------------------------------------------ results


@dataclass(slots=True)
class PartnerReplayResult:
    """One completed replay run, and everything needed to publish it honestly."""

    script: PartnerScript
    session_id: str = ""
    turns: list[dict[str, Any]] = field(default_factory=list)
    agenda_items_covered: list[str] = field(default_factory=list)
    turns_consumed: int = 0
    beliefs_accepted: int = 0
    beliefs_blocked: int = 0
    beliefs_dropped: int = 0
    cards_raised: int = 0
    stop_reason: str = ""
    llm_source: str = "unknown"
    """``cassette`` for a recorded replay, ``vertex`` for a live call. A
    cassette replay is a replayed measurement and is never written up as a
    deployed one."""

    model_ids: list[str] = field(default_factory=list)
    model_calls: int = 0
    paced: bool = True
    speed: float = 1.0
    audience: str = ""
    doctrine_present: bool = False
    opened_at: int = 0
    transcript_path: Path | None = None

    # ------------------------------------------------------------ transcript

    def to_transcript(self) -> dict[str, Any]:
        return {
            "schema": TRANSCRIPT_SCHEMA,
            "_note": _TRANSCRIPT_NOTE,
            "generated_by": "src/baraza/interview/replay.py",
            "generated_at": self.opened_at,
            "generated_at_utc": to_iso(self.opened_at),
            "script": {
                "script_id": self.script.script_id,
                "description": self.script.description,
                "fixture": str(
                    self.script.source_path.relative_to(_REPO)
                    if self.script.source_path.is_relative_to(_REPO)
                    else self.script.source_path
                ),
                "fixture_sha256": self.script.fixture_sha256,
                "canned_turns_available": len(self.script.turns),
                "chars_per_minute": self.script.chars_per_minute,
            },
            "run": {
                "session_id": self.session_id,
                "audience": self.audience,
                "doctrine_present": self.doctrine_present,
                "llm_source": self.llm_source,
                "model_ids": sorted(self.model_ids),
                "model_calls": self.model_calls,
                "paced": self.paced,
                "speed": self.speed,
                "turns_consumed": self.turns_consumed,
                "beliefs_accepted": self.beliefs_accepted,
                "beliefs_blocked": self.beliefs_blocked,
                "beliefs_dropped": self.beliefs_dropped,
                "cards_raised": self.cards_raised,
                "agenda_items_covered": list(self.agenda_items_covered),
                "stop_reason": self.stop_reason,
                "timing_provenance": (
                    "measured in-process during a local replay run"
                    + (
                        "; the model side is a recorded cassette replay"
                        if self.llm_source == "cassette"
                        else ""
                    )
                    + (
                        "; inter-turn gaps are simulated typing pace, not latency"
                        if self.paced
                        else "; pacing disabled, inter-turn gaps are not human"
                    )
                    + ". Not a deployed measurement."
                ),
                "first_visible_token_ms_measures": (
                    "the presentation path only. A planned turn's text is "
                    "already decided before streaming begins, so this is the "
                    "interval a person actually waits before seeing a word — "
                    "not model time-to-first-token, and not a deployed figure."
                ),
            },
            "turns": self.turns,
        }

    def save(self, directory: Path | str = TRANSCRIPT_DIR) -> Path:
        target = Path(directory) / f"{self.script.source_path.stem}.json"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(self.to_transcript(), indent=2) + "\n", encoding="utf-8"
        )
        self.transcript_path = target
        return target

    def describe(self) -> list[str]:
        return [
            f"script             {self.script.script_id}",
            f"agenda items       {len(self.agenda_items_covered)} "
            f"({', '.join(self.agenda_items_covered) or 'none'})",
            f"turns              {len(self.turns)}",
            f"beliefs            {self.beliefs_accepted} accepted, "
            f"{self.beliefs_blocked} blocked, {self.beliefs_dropped} dropped",
            f"divergence cards   {self.cards_raised}",
            f"stopped because    {self.stop_reason}",
        ]


# ------------------------------------------------------------- the harness


class PartnerReplayHarness:
    """Drives a real :class:`PartnerSession` against canned user turns.

    The harness builds the session itself, around a failure-watching client, so
    that no model-layer error the session swallowed can survive into a
    transcript. Everything else — extraction gates, detection, the append-only
    store — is the production code, not a stand-in.
    """

    def __init__(
        self,
        *,
        client: LLMClient,
        agenda: Agenda,
        session_store: SessionStore,
        script: PartnerScript,
        belief_pool: Sequence[Claim] = (),
        doctrine_system_prompt: str = "",
        audience: Audience = Audience.OWNER,
        follow_up_budget: int = FOLLOW_UP_BUDGET,
        speed: float = 1.0,
        paced: bool = True,
        max_agent_turns: int = 200,
        sleeper: Callable[[float], None] = time.sleep,
        clock: Callable[[], float] = time.time,
        on_plan: Callable[[TurnPlan], None] | None = None,
        emit: Callable[[str], None] | None = None,
        on_turn: Callable[[str], None] | None = None,
    ):
        self._watch = _FailureWatchingClient(client)
        self.partner = PartnerSession(
            client=self._watch,
            agenda=agenda,
            session_store=session_store,
            belief_pool=belief_pool,
            doctrine_system_prompt=doctrine_system_prompt,
            audience=audience,
            follow_up_budget=follow_up_budget,
            clock=clock,
        )
        self.script = script
        self.speed = speed
        self.paced = paced
        self.max_agent_turns = max_agent_turns
        self.sleeper = sleeper
        self.on_plan = on_plan
        self.emit = emit
        self.on_turn = on_turn
        self.doctrine_present = bool(doctrine_system_prompt.strip())

    # -------------------------------------------------------------- failures

    def _check_failures(self) -> None:
        if not self._watch.failures:
            return
        rendered = "\n".join(f"  {call}: {err}" for call, err in self._watch.failures)
        raise ReplayPreconditionError(
            "the model layer failed during the replay and the session "
            "swallowed it (it degrades gracefully so a live session does not "
            "hang). No transcript was written.\n"
            f"{rendered}\n"
            "A run that continued here would publish a transcript with missing "
            "turns and belief counts that measure the outage, not the script."
        )

    # ------------------------------------------------------------- recording

    @staticmethod
    def _agent_record(turn: Turn) -> dict[str, Any]:
        return {
            "turn_id": turn.turn_id,
            "index": turn.index,
            "role": turn.role.value,
            "kind": turn.kind.value,
            "text": turn.text,
            "occurred_at": turn.occurred_at,
            "occurred_at_utc": to_iso(turn.occurred_at),
            "agenda_item_id": turn.agenda_item_id,
            "contradiction_id": turn.contradiction_id,
            "cited_claim_ids": list(turn.cited_claim_ids),
            "follow_up_depth": turn.follow_up_depth,
            "first_visible_token_ms": turn.first_token_ms,
            "divergence_card": turn.extra.get("divergence_card"),
        }

    def _user_record(
        self, outcome: PartnerTurnOutcome, *, typing_delay_ms: int
    ) -> dict[str, Any]:
        turn = outcome.user_turn
        return {
            "turn_id": turn.turn_id,
            "index": turn.index,
            "role": turn.role.value,
            "kind": turn.kind.value,
            "text": turn.text,
            "occurred_at": turn.occurred_at,
            "occurred_at_utc": to_iso(turn.occurred_at),
            "agenda_item_id": turn.agenda_item_id,
            "follow_up_depth": turn.follow_up_depth,
            "typing_delay_ms": typing_delay_ms,
            "beliefs": {
                "raw_returned": outcome.raw_returned,
                "accepted": [
                    self._belief_record(c) for c in outcome.accepted
                ],
                "blocked": [
                    self._belief_record(c) for c in outcome.blocked
                ],
                "dropped": [
                    {"reason": reason} for reason, _ in outcome.dropped
                ],
            },
            "cards": [card.to_dict() for card in outcome.cards],
        }

    def _belief_record(self, claim: Claim) -> dict[str, Any]:
        quote = claim.quote_for(self.partner.audience)
        return {
            "claim_id": claim.claim_id,
            "predicate_hint": claim.predicate_hint,
            "rule": claim.predicate,
            "anchor": claim.anchor.key(),
            # Through the boundary, same as every render: a quote this
            # audience may not read is named as unreadable, never leaked.
            "quote": quote if quote is not None else "[not readable by this audience]",
        }

    # -------------------------------------------------------------------- run

    def run(self) -> PartnerReplayResult:
        """Run the session to exhaustion and return the transcript in memory.

        Writing the file is the caller's decision, so a run that fails its own
        preconditions cannot leave a half-transcript behind.
        """
        script = self.script
        script.validate()

        result = PartnerReplayResult(
            script=script,
            paced=self.paced,
            speed=self.speed,
            doctrine_present=self.doctrine_present,
        )

        opening = self.partner.open(emit=self.emit)
        session = self.partner.session
        assert session is not None  # open() just set it
        result.session_id = session.session_id
        result.opened_at = session.opened_at
        result.audience = self.partner.audience.value
        result.agenda_items_covered.append(self.partner.current_item.item_id)
        result.turns.append(self._agent_record(opening))
        self._check_failures()

        turn_index = 0
        agent_turns = 1

        while True:
            if turn_index >= len(script.turns):
                result.stop_reason = "canned turns exhausted"
                break

            canned = script.turns[turn_index]
            turn_index += 1

            delay_ms = (
                script.typing_delay_ms(canned.text, speed=self.speed)
                if self.paced
                else 0
            )
            if delay_ms:
                self.sleeper(delay_ms / 1000.0)
            if self.on_turn is not None:
                self.on_turn(canned.text)

            outcome = self.partner.observe_user_turn(canned.text)
            result.turns.append(
                self._user_record(outcome, typing_delay_ms=delay_ms)
            )
            result.beliefs_accepted += len(outcome.accepted)
            result.beliefs_blocked += len(outcome.blocked)
            result.beliefs_dropped += len(outcome.dropped)
            result.cards_raised += len(outcome.cards)
            self._check_failures()

            plan = self.partner.plan_next(canned.text)
            self._check_failures()
            if plan is None:
                result.stop_reason = "agenda exhausted"
                break

            if self.on_plan is not None:
                self.on_plan(plan)
            turn = self.partner.speak(plan, emit=self.emit)
            result.turns.append(self._agent_record(turn))
            agent_turns += 1

            item_id = self.partner.current_item.item_id
            if item_id not in result.agenda_items_covered:
                result.agenda_items_covered.append(item_id)

            if agent_turns >= self.max_agent_turns:
                result.stop_reason = f"agent-turn cap ({self.max_agent_turns}) reached"
                break

        self.partner.close()

        result.turns_consumed = turn_index
        result.model_calls = self._watch.calls
        result.model_ids = sorted(self._watch.model_ids)

        # A transcript with no model in the loop is not evidence of anything
        # the session does. Refusing here catches the case where every turn
        # short-circuited before a call — which would otherwise write a clean
        # file full of zeroes.
        if not self._watch.sources:
            raise ReplayPreconditionError(
                "the run completed without a single model response. No "
                "transcript was written: a transcript that records no model "
                "call cannot evidence what the session extracts or detects."
            )
        result.llm_source = "+".join(sorted(self._watch.sources))
        self._check_failures()
        return result
