"""BAR-330 AC 1 — the ``--replay`` harness.

The adaptation claim is the one claim in this project that a judge cannot check
by watching the demo. "The agent adapts" looks identical to "the agent has a
parameter named adapt". So the claim is discharged the only way it can be: by
committing raw transcripts of real runs and letting somebody else compute the
number from them.

**Input and output are deliberately different directories.**

``fixtures/interviews/<persona>.json``
    Hand-authored. What the departing officer says. This is a script, and it is
    supposed to be.

``fixtures/transcripts/<persona>.json``
    **Generated by an actual run of this module, and never hand-edited.** The
    harness overwrites the file wholesale on every run, so an edit survives
    exactly until the next run and shows up in the diff of the one after it.
    ``scripts/adaptation_metric.py`` reads these and imports nothing from this
    package, which is what makes the published number reproducible by someone
    who does not trust the application.

**Why the answers arrive on a timer.** An interview is paced by a person. A
harness that dumps twenty answers into the loop in four milliseconds is
exercising a different system than the one a judge watches — the streaming path
never has to hold anyone's attention, and a first-visible-token figure measured
under that load is a figure about nothing. The pace is declared per persona in
characters per minute, the run records whether it was paced and by what
acceleration factor, and any timing derived from a paced run says so.

**Why the two personas are shaped the way they are.** ``AdaptationState`` moves
the follow-up budget on the ratio of answers falling below
``TERSE_CHAR_THRESHOLD``. The terse persona sits entirely below it and drives the
budget up; the expansive persona sits entirely above it and drives the budget
down. That is checked at load time rather than assumed: a fixture that drifted
across the threshold would still produce a transcript, still produce a mean, and
mean nothing. :meth:`Persona.validate` refuses the run instead.

**Why the harness watches for exceptions the interviewer swallows.**
``Interviewer.compose_follow_up`` and ``Interviewer.check_divergence`` catch
everything and return ``None``. That is right for a live interview — losing one
clarifier is cheaper than hanging with a person waiting — and it is exactly
wrong for a transcript about to be published as evidence. A missing cassette
would otherwise yield a clean-looking run with zero follow-ups, a mean depth of
0.0, and no sign that the model was never consulted. So the client is wrapped:
every swallowed failure is recorded, the run aborts at the next turn boundary,
and no transcript is written. A number produced by silent failure is the same
defect as a number typed in by hand.
"""

from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple

from baraza.interview.interviewer import (
    MAX_FOLLOW_UP_DEPTH,
    TERSE_CHAR_THRESHOLD,
    AdaptationState,
    Interviewer,
    TurnPlan,
)
from baraza.interview.session_store import SessionStore
from baraza.llm import LLMClient, LLMResponse
from baraza.reconcile.agenda import Agenda, AgendaItem
from baraza.schema.session import Session, Turn, TurnKind, TurnRole
from baraza.schema.temporal import EpochMillis, to_epoch_millis, to_iso

__all__ = [
    "CannedAnswer",
    "Persona",
    "PersonaError",
    "ReplayPreconditionError",
    "ReplayHarness",
    "ReplayResult",
    "TRANSCRIPT_SCHEMA",
    "PERSONA_DIR",
    "TRANSCRIPT_DIR",
    "load_persona",
    "available_personas",
]

_REPO = Path(__file__).resolve().parents[3]
PERSONA_DIR = _REPO / "fixtures" / "interviews"
TRANSCRIPT_DIR = _REPO / "fixtures" / "transcripts"

TRANSCRIPT_SCHEMA = "baraza.transcript.v1"
"""Versioned because ``scripts/adaptation_metric.py`` is not allowed to import
this module and therefore cannot follow a field rename. The scorer checks this
string and refuses a transcript it does not recognize rather than averaging
whatever it finds."""

INITIAL_FOLLOW_UP_BUDGET = AdaptationState(persona_id="_probe").follow_up_budget
"""Read off the dataclass rather than restated, so the transcript's declared
starting budget cannot drift away from the one the run actually used."""

_TRANSCRIPT_NOTE = (
    "Generated by an actual replay run of src/baraza/interview/replay.py. Not "
    "hand-authored and not hand-edited: the harness rewrites this file whole on "
    "every run, so an edit survives until the next run and is visible in the "
    "diff after it. The metric published from this file is computed by "
    "scripts/adaptation_metric.py, which imports nothing from the application "
    "package."
)


class PersonaError(ValueError):
    """A persona fixture does not embody the style it declares."""


class ReplayPreconditionError(RuntimeError):
    """The run cannot produce an honest transcript, so it produced none.

    Raised for a missing cassette, an auth failure, or any other model-layer
    error the interviewer swallowed. Never downgraded to a warning: a transcript
    written after a swallowed failure is a fabricated measurement wearing a
    generated file's clothes.
    """


# --------------------------------------------------------------- the persona


@dataclass(frozen=True, slots=True)
class CannedAnswer:
    text: str
    note: str = ""

    @property
    def char_count(self) -> int:
        return len(self.text.strip())


@dataclass(frozen=True, slots=True)
class Persona:
    """One departing-officer script, plus the pace it is delivered at."""

    persona_id: str
    role: str
    style: str
    description: str
    chars_per_minute: int
    min_pause_ms: int
    max_pause_ms: int
    answers: Tuple[CannedAnswer, ...]
    source_path: Path
    fixture_sha256: str
    """Digest of the fixture bytes, stamped into the transcript. Ties a published
    number to the exact script that produced it, so "we changed the answers and
    reran" is visible rather than inferable."""

    def validate(self) -> None:
        """Assert the fixture still straddles the threshold it claims to.

        The adaptation is driven by answer length. A terse fixture that grew
        past ``TERSE_CHAR_THRESHOLD`` would stop moving the budget upward and
        the run would still complete, still write a transcript, and still yield
        a mean — one that no longer measures adaptation in the direction the
        file's name promises.
        """
        if self.style not in ("terse", "expansive"):
            raise PersonaError(
                f"{self.source_path}: style {self.style!r} is neither 'terse' nor "
                "'expansive'. The two styles exist to exercise the follow-up "
                "budget in both directions; a third style would exercise nothing."
            )
        if not self.answers:
            raise PersonaError(f"{self.source_path}: no canned answers")

        offenders: List[Tuple[int, int]] = []
        for index, answer in enumerate(self.answers):
            length = answer.char_count
            terse = length < TERSE_CHAR_THRESHOLD
            if (self.style == "terse") != terse:
                offenders.append((index, length))

        if offenders:
            listed = ", ".join(f"#{i} ({n} chars)" for i, n in offenders[:6])
            raise PersonaError(
                f"{self.source_path}: persona declares style {self.style!r} but "
                f"{len(offenders)} answer(s) fall on the wrong side of "
                f"TERSE_CHAR_THRESHOLD ({TERSE_CHAR_THRESHOLD}): {listed}"
                f"{' …' if len(offenders) > 6 else ''}. "
                "Fix the fixture rather than the threshold — the threshold is "
                "what the committed transcripts were scored against."
            )

    def typing_delay_ms(self, text: str, *, speed: float = 1.0) -> int:
        """How long this persona would take to type ``text``.

        Clamped at both ends. The floor keeps a two-word answer from arriving
        instantly, which reads as a machine rather than a person; the ceiling
        keeps a 300-character answer from stalling a demo for a minute. Both
        bounds are declared in the fixture and both are recorded in the
        transcript, so nobody has to guess whether a gap between turns is a
        measurement or a stage direction.
        """
        if speed <= 0:
            return 0
        raw = (len(text) / max(self.chars_per_minute, 1)) * 60_000.0
        clamped = max(self.min_pause_ms, min(self.max_pause_ms, raw))
        return int(clamped / speed)

    def describe(self) -> str:
        lengths = [a.char_count for a in self.answers]
        return (
            f"{self.persona_id} ({self.role}) — {self.style}: "
            f"{len(self.answers)} canned answers, "
            f"{min(lengths)}–{max(lengths)} chars "
            f"(threshold {TERSE_CHAR_THRESHOLD}), "
            f"{self.chars_per_minute} cpm"
        )


def available_personas(directory: Path | str = PERSONA_DIR) -> List[str]:
    return sorted(p.stem for p in Path(directory).glob("*.json"))


def load_persona(
    name_or_path: str | Path, *, directory: Path | str = PERSONA_DIR
) -> Persona:
    """Load and validate a persona fixture.

    Accepts a bare name (``terse``) or a path. Validation runs here rather than
    at first use so a bad fixture fails before a session is opened and before
    any event is appended to the log.
    """
    candidate = Path(name_or_path)
    path = candidate if candidate.suffix == ".json" else Path(directory) / f"{candidate}.json"

    if not path.exists():
        known = available_personas(directory)
        raise FileNotFoundError(
            f"no persona fixture at {path}. "
            f"Known personas in {directory}: {known or '(none)'}"
        )

    raw = path.read_bytes()
    payload = json.loads(raw.decode("utf-8"))
    typing = payload.get("typing") or {}

    persona = Persona(
        persona_id=payload["persona_id"],
        role=payload.get("role", ""),
        style=payload["style"],
        description=payload.get("description", ""),
        chars_per_minute=int(typing.get("chars_per_minute", 240)),
        min_pause_ms=int(typing.get("min_pause_ms", 400)),
        max_pause_ms=int(typing.get("max_pause_ms", 6000)),
        answers=tuple(
            CannedAnswer(text=a["text"], note=a.get("note", ""))
            for a in payload.get("answers", [])
        ),
        source_path=path,
        fixture_sha256=hashlib.sha256(raw).hexdigest(),
    )
    persona.validate()
    return persona


# ------------------------------------------------------- the failure watcher


class _FailureWatchingClient(LLMClient):
    """Delegating client that remembers what the interviewer chose to forget.

    See the module docstring. This exists because a swallowed ``CassetteMiss``
    and a genuinely settled question are indistinguishable from inside the turn
    loop, and one of them invalidates the transcript.
    """

    def __init__(self, inner: LLMClient):
        self.inner = inner
        self.failures: List[Tuple[str, str]] = []
        self.sources: set[str] = set()
        self.model_ids: set[str] = set()
        self.calls = 0

    def _record(self, response: LLMResponse) -> LLMResponse:
        self.calls += 1
        self.sources.add(response.source)
        self.model_ids.add(response.model_id)
        return response

    def generate(self, **kwargs: Any) -> LLMResponse:
        try:
            return self._record(self.inner.generate(**kwargs))
        except Exception as exc:  # noqa: BLE001 - recorded, then re-raised
            self.failures.append((f"generate(role={kwargs.get('role')!r})", str(exc)))
            raise

    def stream(self, **kwargs: Any) -> Iterator[str]:
        try:
            yield from self.inner.stream(**kwargs)
        except Exception as exc:  # noqa: BLE001
            self.failures.append((f"stream(role={kwargs.get('role')!r})", str(exc)))
            raise


# ------------------------------------------------------------------ results


@dataclass(slots=True)
class ReplayResult:
    """One completed replay run, and everything needed to publish it honestly."""

    persona: Persona
    session: Session
    adaptation: AdaptationState
    turns: List[Dict[str, Any]] = field(default_factory=list)
    agenda_items_covered: List[str] = field(default_factory=list)
    answers_consumed: int = 0
    stop_reason: str = ""
    llm_source: str = "unknown"
    """``cassette`` for a recorded replay, ``vertex`` for a live call. A cassette
    replay is a replayed measurement and is never written up as a deployed one."""

    model_ids: List[str] = field(default_factory=list)
    model_calls: int = 0
    paced: bool = True
    speed: float = 1.0
    audience: str = ""
    transcript_path: Optional[Path] = None

    @property
    def agent_turns(self) -> List[Dict[str, Any]]:
        return [t for t in self.turns if t["role"] == TurnRole.AGENT.value]

    @property
    def follow_up_turns(self) -> List[Dict[str, Any]]:
        return [t for t in self.agent_turns if t["kind"] == TurnKind.FOLLOW_UP.value]

    def budget_trajectory(self) -> List[int]:
        seen: List[int] = []
        for turn in self.turns:
            budget = turn["adaptation"]["follow_up_budget"]
            if not seen or seen[-1] != budget:
                seen.append(budget)
        return seen

    def adaptation_moment_turn_ids(self) -> List[str]:
        """Turns where the budget moved, by turn ID.

        BAR-330 AC 3 wants a judge to be able to open the transcript at "turn
        t-14". The scorer derives the same list independently from per-turn
        state; this accessor exists for the console, not for the published
        number.
        """
        moments: List[str] = []
        previous: Optional[int] = None
        for turn in self.turns:
            budget = turn["adaptation"]["follow_up_budget"]
            if previous is not None and budget != previous:
                moments.append(turn["turn_id"])
            previous = budget
        return moments

    # ------------------------------------------------------------ transcript

    def to_transcript(self) -> Dict[str, Any]:
        return {
            "schema": TRANSCRIPT_SCHEMA,
            "_note": _TRANSCRIPT_NOTE,
            "generated_by": "src/baraza/interview/replay.py",
            "generated_at": self.session.opened_at,
            "generated_at_utc": to_iso(self.session.opened_at),
            "persona": {
                "persona_id": self.persona.persona_id,
                "role": self.persona.role,
                "style": self.persona.style,
                "description": self.persona.description,
                "fixture": str(
                    self.persona.source_path.relative_to(_REPO)
                    if self.persona.source_path.is_relative_to(_REPO)
                    else self.persona.source_path
                ),
                "fixture_sha256": self.persona.fixture_sha256,
                "canned_answers_available": len(self.persona.answers),
                "chars_per_minute": self.persona.chars_per_minute,
            },
            "run": {
                "session_id": self.session.session_id,
                "audience": self.audience,
                "llm_source": self.llm_source,
                "model_ids": sorted(self.model_ids),
                "model_calls": self.model_calls,
                "paced": self.paced,
                "speed": self.speed,
                "answers_consumed": self.answers_consumed,
                "agenda_items_covered": list(self.agenda_items_covered),
                "stop_reason": self.stop_reason,
                "timing_provenance": (
                    "measured in-process during a local replay run"
                    + (
                        "; the model side is a recorded cassette replay"
                        if self.llm_source == "cassette"
                        else ""
                    )
                    + (
                        "; inter-turn gaps are simulated typing pace, not latency"
                        if self.paced
                        else "; pacing disabled, inter-turn gaps are not human"
                    )
                    + ". Not a deployed measurement."
                ),
                "first_visible_token_ms_measures": (
                    "the presentation path only. A planned turn's text is already "
                    "decided before streaming begins, so this is the interval a "
                    "person actually waits before seeing a word — not model "
                    "time-to-first-token, and not a deployed figure."
                ),
            },
            "thresholds": {
                "terse_char_threshold": TERSE_CHAR_THRESHOLD,
                "max_follow_up_depth": MAX_FOLLOW_UP_DEPTH,
                "initial_follow_up_budget": INITIAL_FOLLOW_UP_BUDGET,
            },
            "turns": self.turns,
        }

    def save(self, directory: Path | str = TRANSCRIPT_DIR) -> Path:
        target = Path(directory) / f"{self.persona.source_path.stem}.json"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(self.to_transcript(), indent=2) + "\n", encoding="utf-8"
        )
        self.transcript_path = target
        return target

    def describe(self) -> List[str]:
        agent = len(self.agent_turns)
        depth_total = sum(t["follow_up_depth"] for t in self.agent_turns)
        lines = [
            f"persona            {self.persona.persona_id} ({self.persona.style})",
            f"agenda items       {len(self.agenda_items_covered)} "
            f"({', '.join(self.agenda_items_covered) or 'none'})",
            f"turns              {len(self.turns)} "
            f"({agent} agent, {len(self.turns) - agent} officer)",
            f"follow-ups         {len(self.follow_up_turns)}",
            "follow-up budget   "
            + " → ".join(str(b) for b in self.budget_trajectory()),
            f"stopped because    {self.stop_reason}",
        ]
        moments = self.adaptation_moment_turn_ids()
        lines.append(
            "adaptation moment  "
            + (", ".join(f"turn {t}" for t in moments) if moments else "none in this run")
        )
        # Deliberately NOT called "the metric". The published figure comes from
        # scripts/adaptation_metric.py over the committed transcript; this is an
        # in-process convenience so a demo watcher sees the same shape.
        if agent:
            lines.append(
                f"in-process check   sum(depth)/agent turns = {depth_total}/{agent} "
                f"= {depth_total / agent:.4f}  "
                "(published figure comes from make adaptation-metric)"
            )
        return lines


# ------------------------------------------------------------- the harness


class ReplayHarness:
    """Drives a real ``Interviewer`` against canned answers on a timer."""

    def __init__(
        self,
        *,
        interviewer: Interviewer,
        agenda: Agenda,
        session_store: SessionStore,
        persona: Persona,
        speed: float = 1.0,
        paced: bool = True,
        max_items: Optional[int] = None,
        max_agent_turns: int = 200,
        sleeper: Callable[[float], None] = time.sleep,
        clock: Callable[[], float] = time.time,
        on_plan: Optional[Callable[[TurnPlan], None]] = None,
        emit: Optional[Callable[[str], None]] = None,
        on_answer: Optional[Callable[[str], None]] = None,
    ):
        # The interviewer is rebuilt around a watching client rather than having
        # its client swapped in place, so a caller that kept a reference to the
        # original object still holds an object that behaves as it did.
        self._watch = _FailureWatchingClient(interviewer.client)
        self.interviewer = Interviewer(
            self._watch, interviewer.state, audience=interviewer.audience
        )
        self.agenda = agenda
        self.session_store = session_store
        self.persona = persona
        self.speed = speed
        self.paced = paced
        self.max_items = max_items
        self.max_agent_turns = max_agent_turns
        self.sleeper = sleeper
        self.clock = clock
        self.on_plan = on_plan
        self.emit = emit
        self.on_answer = on_answer
        self._last_instant: Optional[EpochMillis] = None

    # One agenda item may legitimately absorb its opening question, a full
    # follow-up budget of clarifiers, and a divergence turn. Past that the loop
    # is not interviewing, it is circling: `plan_next` runs the divergence check
    # before the depth check, so a testimony the adjudicator keeps flagging can
    # hold the floor indefinitely and drain the canned answers on one topic.
    # Advancing the agenda here is a pacing decision, which is the harness's job.
    @property
    def per_item_turn_cap(self) -> int:
        return 1 + MAX_FOLLOW_UP_DEPTH + 2

    # ---------------------------------------------------------------- clock

    def _now(self) -> EpochMillis:
        """Strictly increasing epoch millis.

        Two turns inside the same millisecond would give the transcript a
        non-total order under BAR-309's integer comparison, and the scorer sorts
        on this field. Nudging forward is honest at millisecond resolution and
        keeps the ordering a property of the data rather than of the reader.
        """
        instant = to_epoch_millis(self.clock(), field="replay.turn")
        if self._last_instant is not None and instant <= self._last_instant:
            instant = self._last_instant + 1
        self._last_instant = instant
        return instant

    # -------------------------------------------------------------- failures

    def _check_failures(self) -> None:
        if not self._watch.failures:
            return
        rendered = "\n".join(f"  {call}: {err}" for call, err in self._watch.failures)
        raise ReplayPreconditionError(
            "the model layer failed during the replay and the interviewer "
            "swallowed it (it catches everything so a live interview does not "
            "hang). No transcript was written.\n"
            f"{rendered}\n"
            "A run that continued here would publish a transcript with missing "
            "follow-ups and a mean depth that measures the outage, not the "
            "persona."
        )

    # ------------------------------------------------------------------ turns

    def _record(
        self,
        turn: Turn,
        *,
        adaptation: AdaptationState,
        adaptation_change: Optional[str] = None,
        typing_delay_ms: Optional[int] = None,
    ) -> Dict[str, Any]:
        return {
            "turn_id": turn.turn_id,
            "index": turn.index,
            "role": turn.role.value,
            "kind": turn.kind.value,
            "text": turn.text,
            "occurred_at": turn.occurred_at,
            "occurred_at_utc": to_iso(turn.occurred_at),
            "follow_up_depth": turn.follow_up_depth,
            "agenda_item_id": turn.agenda_item_id,
            "contradiction_id": turn.contradiction_id,
            "cited_claim_ids": list(turn.cited_claim_ids),
            "char_count": len(turn.text.strip()),
            "first_visible_token_ms": turn.first_token_ms,
            "typing_delay_ms": typing_delay_ms,
            "adaptation": adaptation.to_dict(),
            "adaptation_change": adaptation_change,
        }

    def _agent_turn(
        self, session: Session, plan: TurnPlan, adaptation: AdaptationState
    ) -> Tuple[Turn, Dict[str, Any]]:
        occurred_at = self._now()
        first_token_ms: Optional[int] = None

        if self.on_plan is not None:
            self.on_plan(plan)
        for chunk, elapsed_ms in self.interviewer.stream_turn(plan):
            if first_token_ms is None:
                first_token_ms = elapsed_ms
            if self.emit is not None:
                self.emit(chunk)

        turn = Turn.create(
            session_id=session.session_id,
            index=session.next_index,
            role=TurnRole.AGENT,
            kind=plan.kind,
            text=plan.text,
            occurred_at=occurred_at,
            agenda_item_id=plan.agenda_item_id,
            contradiction_id=plan.contradiction_id,
            cited_claim_ids=plan.cited_claim_ids,
            follow_up_depth=plan.follow_up_depth,
            first_token_ms=first_token_ms,
            extra={
                # The budget the turn ran under, stamped at the moment it ran.
                # Reconstructing it later from the answer history would be a
                # second implementation of the adaptation rule, and the two
                # would eventually disagree.
                "follow_up_budget": adaptation.follow_up_budget,
                "divergence": (
                    None
                    if plan.divergence is None
                    else {
                        "claim_id": plan.divergence.conflicting_claim_id,
                        "anchor": plan.divergence.conflicting_anchor,
                        "confidence": plan.divergence.confidence,
                    }
                ),
            },
        )
        # Externalized BEFORE the answer is solicited (BAR-334): the window in
        # which this turn exists only in memory closes here.
        session.turns.append(turn)
        self.session_store.append_turn(turn)
        return turn, self._record(turn, adaptation=adaptation)

    def _officer_turn(
        self,
        session: Session,
        *,
        answer: CannedAnswer,
        agent_turn: Turn,
        adaptation: AdaptationState,
    ) -> Tuple[Turn, Dict[str, Any], Optional[str]]:
        delay_ms = (
            self.persona.typing_delay_ms(answer.text, speed=self.speed)
            if self.paced
            else 0
        )
        if delay_ms:
            self.sleeper(delay_ms / 1000.0)

        occurred_at = self._now()
        turn = Turn.create(
            session_id=session.session_id,
            index=session.next_index,
            role=TurnRole.OFFICER,
            kind=TurnKind.ANSWER,
            text=answer.text,
            occurred_at=occurred_at,
            agenda_item_id=agent_turn.agenda_item_id,
            contradiction_id=agent_turn.contradiction_id,
            follow_up_depth=agent_turn.follow_up_depth,
            extra={"canned": True, "persona_id": self.persona.persona_id},
        )
        session.turns.append(turn)
        self.session_store.append_turn(turn)

        if self.on_answer is not None:
            self.on_answer(answer.text)

        change = adaptation.observe(answer.text, turn_id=turn.turn_id)
        return (
            turn,
            self._record(
                turn,
                adaptation=adaptation,
                adaptation_change=change,
                typing_delay_ms=delay_ms,
            ),
            change,
        )

    # -------------------------------------------------------------------- run

    def run(self) -> ReplayResult:
        """Run the interview to exhaustion and return the transcript in memory.

        Writing the file is the caller's decision, so a run that fails its own
        preconditions cannot leave a half-transcript behind.
        """
        persona = self.persona
        persona.validate()

        if not self.agenda.items:
            raise ReplayPreconditionError(
                "the agenda is empty. There is nothing to interview about, and a "
                "transcript of an interview that asked nothing would still "
                "average to a number. Run `make demo-agenda` first."
            )

        session = self.session_store.open(
            persona_id=persona.persona_id, opened_at=self._now()
        )
        adaptation = AdaptationState(persona_id=persona.persona_id)
        items_by_id = {item.item_id: item for item in self.agenda.items}

        plan = self.interviewer.opening_turn(self.agenda, session)
        current_item = items_by_id[plan.agenda_item_id]

        result = ReplayResult(
            persona=persona,
            session=session,
            adaptation=adaptation,
            agenda_items_covered=[current_item.item_id],
            paced=self.paced,
            speed=self.speed,
            audience=self.interviewer.audience.value,
        )

        answer_index = 0
        turns_on_item = 0

        while True:
            if len(session.agent_turns()) >= self.max_agent_turns:
                result.stop_reason = f"agent-turn cap ({self.max_agent_turns}) reached"
                break

            agent_turn, agent_record = self._agent_turn(session, plan, adaptation)
            result.turns.append(agent_record)
            turns_on_item += 1
            self._check_failures()

            if answer_index >= len(persona.answers):
                result.stop_reason = "canned answers exhausted"
                break

            answer = persona.answers[answer_index]
            answer_index += 1
            _, officer_record, _ = self._officer_turn(
                session, answer=answer, agent_turn=agent_turn, adaptation=adaptation
            )
            result.turns.append(officer_record)

            if turns_on_item >= self.per_item_turn_cap:
                nxt = self._next_item(current_item)
                if nxt is None:
                    result.stop_reason = "agenda exhausted"
                    break
                plan = self._agenda_plan(nxt)
            else:
                plan = self.interviewer.plan_next(
                    agenda=self.agenda,
                    session=session,
                    adaptation=adaptation,
                    last_answer=answer.text,
                    current_item=current_item,
                    current_depth=agent_turn.follow_up_depth,
                )
                self._check_failures()
                if plan is None:
                    result.stop_reason = "agenda exhausted"
                    break

            if plan.agenda_item_id and plan.agenda_item_id != current_item.item_id:
                current_item = items_by_id[plan.agenda_item_id]
                turns_on_item = 0
                if (
                    self.max_items is not None
                    and len(result.agenda_items_covered) >= self.max_items
                ):
                    result.stop_reason = f"item budget ({self.max_items}) reached"
                    break
                result.agenda_items_covered.append(current_item.item_id)

        self.session_store.close(session, closed_at=self._now())

        result.answers_consumed = answer_index
        result.model_calls = self._watch.calls
        result.model_ids = sorted(self._watch.model_ids)

        # A transcript with no model in the loop is not evidence of anything the
        # interviewer does. Refusing here catches the case where every turn
        # short-circuited before a call — which would otherwise write a clean
        # file full of zeroes.
        if not self._watch.sources:
            raise ReplayPreconditionError(
                "the run completed without a single model response. No "
                "transcript was written: a transcript that records no model "
                "call cannot evidence how the interviewer adapts."
            )
        result.llm_source = "+".join(sorted(self._watch.sources))
        self._check_failures()
        return result

    # ------------------------------------------------------------- agenda nav

    def _next_item(self, current: AgendaItem) -> Optional[AgendaItem]:
        remaining = [i for i in self.agenda.items if i.item_id > current.item_id]
        return remaining[0] if remaining else None

    @staticmethod
    def _agenda_plan(item: AgendaItem) -> TurnPlan:
        return TurnPlan(
            kind=TurnKind.AGENDA,
            text=item.question,
            agenda_item_id=item.item_id,
            contradiction_id=item.contradiction_id,
            cited_claim_ids=list(item.cited_claim_ids),
            follow_up_depth=0,
        )
